source: ~/workspace/upload
workingDirectory: /var/local/vms/deploy
projects:
  - battery
  - nexus
  - command
  - cybernetics
  - nydus
  - overlord
  - bunker
  - observatory
  - sunken
dependency: "[battery,observatory]-nexus-sunken-command-[cybernetics,nydus,overlord,bunker]"
allowCommand: java
completedMessage: "completed to run {prj}!!"
waitTime: 20
execOption:
  - "-Xmx512m"
  - "-Xms256m"
  - "-Dspring.profiles.active=local"