source: ~/workspace/upload
projects:
  - battery
  - nexus
  - command
  - cybernetics
  - nydus
  - overlord
  - bunker
  - observatory
  - sunken
profile: localization
dependency: "[battery,observatory]-nexus-sunken-command"